name: Generate snake animation

on:
  schedule: # thực thi mỗi 12 giờ
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark  # Tạo trực tiếp trong thư mục dist

      - name: Create output directory if not exists
        run: mkdir -p ./dist

      # Vì tệp được tạo trực tiếp vào dist, bước di chuyển không còn cần thiết nữa
      # Đã xóa bước di chuyển

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
